name: Build Debos and run tests
on: [pull_request, push]

jobs:
  build-test:
    name: Build Debos and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Build container
        run: docker build -f docker/Dockerfile -t godebos/debos .

      - name: Run unit tests inside container
        run: docker-compose -f docker/unit-tests.test.yml up --build

      - name: Run test recipes inside container
        run: docker-compose -f docker/recipes.test.yml up --build
